//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semenova_MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public int Product_ID { get; set; }
        public double Count { get; set; }
        public System.DateTime Date { get; set; }
        public int Sotrudnik_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
