//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semenova_MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int PartherProduct_ID { get; set; }
        public int Partner_ID { get; set; }
        public int Product_ID { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
        public int Quantity { get; internal set; }
    }
}
