//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semenova_MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostavshchikMaterialHistory
    {
        public int PostavshchikMaterialHistory1 { get; set; }
        public int Postavshchik_ID { get; set; }
        public int Material_ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Count { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Postavshchik Postavshchik { get; set; }
    }
}
