//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semenova_MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MaterialProduct = new HashSet<MaterialProduct>();
            this.Order = new HashSet<Order>();
            this.PartnerProduct = new HashSet<PartnerProduct>();
            this.PartnerSalesHistory = new HashSet<PartnerSalesHistory>();
        }
    
        public int Product_ID { get; set; }
        public int ProductType_ID { get; set; }
        public string Product_Name { get; set; }
        public string Article { get; set; }
        public decimal Min_Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight_Without_Packaging { get; set; }
        public Nullable<double> Weight_From_Packaging { get; set; }
        public string Quality_Certificate { get; set; }
        public string Standard_Number { get; set; }
        public string Сhange_History_Min_Price { get; set; }
        public string Production_Time { get; set; }
        public Nullable<decimal> Cost_Price { get; set; }
        public Nullable<int> Workshop_Number { get; set; }
        public Nullable<int> Kol_People_Production { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProduct> MaterialProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerSalesHistory> PartnerSalesHistory { get; set; }
        public virtual Product_Type Product_Type { get; set; }
    }
}
