//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semenova_MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Sotrudnik_ID { get; set; }
        public string Sotrudnik_Surname { get; set; }
        public string Sotrudnik_Name { get; set; }
        public string Sotrudnik_Patronymic { get; set; }
        public string Birthday { get; set; }
        public string Seria_Pasport { get; set; }
        public string Nomer_Pasport { get; set; }
        public string Bank { get; set; }
        public string Family { get; set; }
        public string Health { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
